[[session]]
name = "echo"
path = "~/src/echo"
startup_command = ". ~/.config/sesh/scripts/node-app.sh"

[[session]]
name = "neovim config"
path = "~/.config/nvim"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "top"
startup_command = "btop"

# [[default session]]
# startup_command = "nvim ."
# preview_command = "eza --all --git --icons --color=always {}"
#
