prSections:
- title: My Pull Requests
  filters: is:open author:@me
- title: Work Pending
  filters: is:open review-requested:@me org:glg
- title: Work Involved
  filters: is:open involves:@me -author:@me org:glg
- title: Other Pending
  filters: is:open review-requested:@me -org:glg
- title: Other Involved
  filters: is:open involves:@me -author:@me -org:glg
- title: Pending Verification
  filters: is:merged author:@me -label:"1 - Deployment Verified" repo:glg/aws-infrastructure merged:>=2024-01-01
issuesSections:
- title: SRE Roadmap
  filters: is:open repo:glg/sre-roadmap
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    grow: true
    width: 60
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        grow: true
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: false
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues:
    - key: B
      command: >
        tmux display-popup -d {{.RepoPath}} -w 65 -h 10 -E 'ghprb {{.IssueNumber}}'
    - key: e
      command: >
        tmux new-window -c {{.RepoPath}} 'nvim -c ":silent Octo issue edit {{.IssueNumber}}"'
    - key: i
      command: >
        tmux display-popup -d {{.RepoPath}} -w 80% -h 90% -E 'nvim -c ":silent Octo issue create"'
  prs:
    - key: O
      command: >
        tmux new-window -c {{.RepoPath}} 'nvim -c ":silent Octo pr edit {{.PrNumber}}"'
repoPaths:
  glg/*: ~/src/*
pager:
  diff: "delta"
smartFilteringAtLaunch: false
theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#a6adc8"
      inverted: "#242347"
      faint: "#bac2de"
      warning: "#f9e2af"
      success: "#a6e3a1"
    background:
      selected: "#313244"
    border:
      primary: "#89b4fa"
      secondary: "#b4befe"
      faint: "#313244"
