live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[colors.primary]
background = "#000000"

[window]
opacity = 0.8

[font]
size = 12
normal = { family = "Monaspace Argon", style = "Light" }
bold = { family = "Monaspace Argon", style = "Semibold" }
italic = { family = "Monaspace Radon", style = "Light" }
bold_italic = { family = "Monaspace Radon", style = "Semibold" }

[cursor]
vi_mode_style = { shape="Beam", blinking="Off"}
