#!/usr/bin/env bash
echo
echo "Installing rust..."
echo
(
  curl https://sh.rustup.rs -sSf | RUSTUP_INIT_SKIP_PATH_CHECK=yes sh -s -- -y
  PATH=${HOME}/.cargo/bin:$PATH
  rustup component add rls rust-analysis rust-src
  rustup install beta
  rustup install nightly
  rustup +nightly component add rust-analyzer-preview rust-src
  source ${HOME}/.cargo/env
  is_bin_in_path i3 && cargo install xidlehook --bins
  is_bin_in_path i3 && cargo install i3-auto-layout
  cargo install \
    navi \
    exa \
    fnm \
    ripgrep \
    bat \
    sd \
    du-dust \
    pastel \
    topgrade \
    zoxide \
    git-delta \
    gping \
    jless \
    fd-find
)
